package com.debanshu777.caraml.core.ui.icons

import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp

/** Generated by scripts/generate_app_icons.py from composeResources/files/icons.
 * CaraML glyphs: 24px grid, 2px rounded strokes, shared by all platforms. */
object AppIcons {
    val Back: ImageVector = outline("CaraML.Back", "M14 5l-7 7 7 7M7 12h14", autoMirror = true)
    val Block: ImageVector = outline("CaraML.Block", "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z", "m6 6 12 12")
    val Chat: ImageVector = outline("CaraML.Chat", "M5 4h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H9l-6 4V6a2 2 0 0 1 2-2Z", "M7 9h10m-10 4h6")
    val Check: ImageVector = outline("CaraML.Check", "m4 12 5 5L20 6")
    val CheckCircle: ImageVector = outline("CaraML.CheckCircle", "M21 11v1a9 9 0 1 1-5-8", "m8 11 4 4L21 5")
    val Checkbox: ImageVector = outline("CaraML.Checkbox", "M3 3h18v18H3Z", "m7 12 3 3 7-7")
    val CheckboxEmpty: ImageVector = outline("CaraML.CheckboxEmpty", "M3 3h18v18H3Z")
    val ChevronDown: ImageVector = outline("CaraML.ChevronDown", "m5 9 7 7 7-7")
    val ChevronRight: ImageVector = outline("CaraML.ChevronRight", "m9 5 7 7-7 7", autoMirror = true)
    val Circle: ImageVector = outline("CaraML.Circle", "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z")
    val Clock: ImageVector = outline("CaraML.Clock", "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z", "M12 6v6l4 2")
    val Close: ImageVector = outline("CaraML.Close", "m6 6 12 12M18 6 6 18")
    val Compute: ImageVector = outline("CaraML.Compute", "M6 6h12v12H6Z", "M9 9h6v6H9ZM9 2v4m6-4v4M9 18v4m6-4v4M2 9h4m-4 6h4m12-6h4m-4 6h4")
    val Copy: ImageVector = outline("CaraML.Copy", "M9 8h12v13H9Z", "M15 5V2H3v13h3")
    val Create: ImageVector = outline("CaraML.Create", "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z", "m15 5 4 4")
    val Delete: ImageVector = outline("CaraML.Delete", "M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7")
    val Device: ImageVector = outline("CaraML.Device", "M8 2h8a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2Z", "M10 5h4m-3 14h2")
    val Download: ImageVector = outline("CaraML.Download", "M12 3v12m-5-5 5 5 5-5", "M4 16v4h16v-4")
    val Favorite: ImageVector = outline("CaraML.Favorite", "M12 21 3.5 12.5a5.5 5.5 0 0 1 8.5-7 5.5 5.5 0 0 1 8.5 7Z")
    val Filters: ImageVector = outline("CaraML.Filters", "M3 6h7m4 0h7M3 18h11m4 0h3", "M10 3v6m4 6v6")
    val Forward: ImageVector = outline("CaraML.Forward", "M3 12h14m-7-7 7 7-7 7", autoMirror = true)
    val Help: ImageVector = outline("CaraML.Help", "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z", "M9 8a3 3 0 0 1 6 1c0 2-3 2-3 4m0 4v.1")
    val Hourglass: ImageVector = outline("CaraML.Hourglass", "M6 3h12m-12 18h12M7 3v4l10 10v4M17 3v4L7 17v4")
    val Image: ImageVector = outline("CaraML.Image", "M4 3h16a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Z", "m3 16 5-5 4 4 3-3 6 6", "M17 7v.1")
    val Info: ImageVector = outline("CaraML.Info", "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z", "M12 11v6m0-10v.1")
    val Memory: ImageVector = outline("CaraML.Memory", "M5 6h14a2 2 0 0 1 2 2v9H3V8a2 2 0 0 1 2-2Z", "M7 10v3m5-3v3m5-3v3M6 17v3m4-3v3m4-3v3m4-3v3")
    val Menu: ImageVector = outline("CaraML.Menu", "M4 6h16M4 12h12M4 18h16")
    val Models: ImageVector = outline("CaraML.Models", "M2.97 12.92A2 2 0 0 0 2 14.63v3.24a2 2 0 0 0 .97 1.71l3 1.8a2 2 0 0 0 2.06 0L12 19v-5.5l-5-3-4.03 2.42Z", "m7 16.5-4.74-2.85", "m7 16.5 5-3", "M7 16.5v5.17", "M12 13.5V19l3.97 2.38a2 2 0 0 0 2.06 0l3-1.8a2 2 0 0 0 .97-1.71v-3.24a2 2 0 0 0-.97-1.71L17 10.5l-5 3Z", "m17 16.5-5-3", "m17 16.5 4.74-2.85", "M17 16.5v5.17", "M7.97 4.42A2 2 0 0 0 7 6.13v4.37l5 3 5-3V6.13a2 2 0 0 0-.97-1.71l-3-1.8a2 2 0 0 0-2.06 0l-3 1.8Z", "M12 8 7.26 5.15", "m12 8 4.74-2.85", "M12 13.5V8")
    val Pause: ImageVector = outline("CaraML.Pause", "M8 5v14M16 5v14")
    val Play: ImageVector = outline("CaraML.Play", "m8 4 12 8-12 8Z")
    val Profile: ImageVector = outline("CaraML.Profile", "M5 4h14v16H5Z", "M8 8h8m-8 4h5m-5 4h8")
    val Refresh: ImageVector = outline("CaraML.Refresh", "M20 10a8 8 0 0 0-14-5L3 8m0-5v5h5", "M4 14a8 8 0 0 0 14 5l3-3m0 5v-5h-5")
    val Search: ImageVector = outline("CaraML.Search", "M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0Z", "m15 15 6 6")
    val Send: ImageVector = outline("CaraML.Send", "m3 3 19 9-19 9 4-9-4-9Z", "M7 12h15", autoMirror = true)
    val Settings: ImageVector = outline("CaraML.Settings", "M10 5H3", "M12 19H3", "M14 3v4", "M16 17v4", "M21 12h-9", "M21 19h-5", "M21 5h-7", "M8 10v4", "M8 12H3")
    val Spark: ImageVector = outline("CaraML.Spark", "m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z")
    val Speed: ImageVector = outline("CaraML.Speed", "M4 19a10 10 0 1 1 16 0", "m12 14 5-6M5 13h1m1-6 1 1m4-4v1m7 8h-1")
    val Stop: ImageVector = outline("CaraML.Stop", "M6 6h12v12H6Z")
    val Storage: ImageVector = outline("CaraML.Storage", "M5 4h14l2 9v6a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-6L5 4Z", "M3 13h18M6 17h4m6 0h2")
    val Text: ImageVector = outline("CaraML.Text", "M4 5h16M12 5v15m-4 0h8")
    val Upload: ImageVector = outline("CaraML.Upload", "M12 17V5m-5 5 5-5 5 5", "M4 18v3h16v-3")
    val Video: ImageVector = outline("CaraML.Video", "M4 5h16v14H4Z", "M4 9h16m-12-4 4 4m2-4 4 4m-8 3 5 3-5 3Z")
    val Warning: ImageVector = outline("CaraML.Warning", "M10.3 3.8 2.6 18a2 2 0 0 0 1.8 3h15.2a2 2 0 0 0 1.8-3L13.7 3.8a2 2 0 0 0-3.4 0Z", "M12 9v4m0 4v.1")
    val Wrench: ImageVector = outline("CaraML.Wrench", "m14 6 4-4a6 6 0 0 0-7 8L3 18a2 2 0 0 0 3 3l8-8a6 6 0 0 0 8-7l-4 4Z")
}

private fun outline(name: String, vararg paths: String, autoMirror: Boolean = false): ImageVector =
    ImageVector.Builder(name, 24.dp, 24.dp, 24f, 24f, autoMirror = autoMirror).apply {
        paths.forEach { addPath(addPathNodes(it), fill = null, stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) }
    }.build()
