"""Regenerate the multiplatform ImageVectors from CaraML's bundled SVG path assets."""
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "composeApp/src/commonMain/composeResources/files/icons"
TARGET = ROOT / "composeApp/src/commonMain/kotlin/com/debanshu777/caraml/core/ui/icons/AppIcons.kt"
lines = [
    "package com.debanshu777.caraml.core.ui.icons", "",
    "import androidx.compose.ui.graphics.*",
    "import androidx.compose.ui.graphics.vector.ImageVector",
    "import androidx.compose.ui.graphics.vector.addPathNodes",
    "import androidx.compose.ui.unit.dp", "",
    "/** Generated by scripts/generate_app_icons.py from composeResources/files/icons.",
    " * CaraML glyphs: 24px grid, 2px rounded strokes, shared by all platforms. */",
    "object AppIcons {",
]
for source in sorted(SOURCE.glob("ic_*.svg")):
    root = ET.parse(source).getroot()
    if root.attrib.get("viewBox") != "0 0 24 24":
        raise ValueError(f"Unexpected icon viewport: {source.name}")
    name = "".join(part.capitalize() for part in source.stem[3:].split("_"))
    paths = []
    for child in root:
        if child.tag != "{http://www.w3.org/2000/svg}path" or set(child.attrib) != {"d"}:
            raise ValueError(f"Only path data is supported: {source.name}")
        value = child.attrib["d"]
        if any(char in value for char in ('"', '\\', '$', '\n', '\r')):
            raise ValueError(f"Invalid path data: {source.name}")
        paths.append('"' + value + '"')
    mirror = ", autoMirror = true" if name in {"Back", "Forward", "ChevronRight", "Send"} else ""
    lines.append(f'    val {name}: ImageVector = outline("CaraML.{name}", ' + ", ".join(paths) + mirror + ")")
lines += ["}", "", "private fun outline(name: String, vararg paths: String, autoMirror: Boolean = false): ImageVector =",
    "    ImageVector.Builder(name, 24.dp, 24.dp, 24f, 24f, autoMirror = autoMirror).apply {",
    "        paths.forEach { addPath(addPathNodes(it), fill = null, stroke = SolidColor(Color.Black),",
    "            strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) }",
    "    }.build()", ""]
TARGET.write_text("\n".join(lines))
